services:
  postgres:
    image: postgres:latest
    container_name: napp_postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
    networks:
      - fullstack
  api:
    container_name: napp_api
    build: .
    ports:
      - 8888:8888
    restart: always
    depends_on:
      - postgres    
    networks:
      - fullstack

volumes:
  database_dockerizing:

networks:
  fullstack:
    driver: bridge